In [9]:
pip install numpy pandas scikit-learn matplotlib seaborn

In [10]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
data = pd.DataFrame(data = iris.data, columns = iris.feature_names)
data['target'] = iris.target

#eksplorasi dataset
print(data.head())
print(data.info())
print(data.describe())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float

In [18]:
#preprocessing the data
from sklearn.preprocessing import StandardScaler

#pisahkan feature dengan target
x = data.drop('target',axis=1)
y = data['target']

#scale the features
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [22]:
#splitting the data
from sklearn.model_selection import train_test_split

#split dataset ke traning data dan testing data
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
#menerapkan algoritma
from sklearn.ensemble import RandomForestClassifier

#inisialisasi model
model = RandomForestClassifier(random_state=42)

In [24]:
#train model
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [25]:
#evaluasi model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
#membuat prediksi pada test data
y_pred = model.predict(x_test)

#evaluate model
print("akurasi", accuracy_score(y_test, y_pred))
print("laporan klasifikasi:")
print(classification_report(y_test,y_pred))
print("confusion matrix:")
print(confusion_matrix(y_test,y_pred))

akurasi 1.0
laporan klasifikasi:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [28]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30]
}
grid_search = GridSearchCV(model, param_grid, cv=5,scoring = 'accuracy')
grid_search.fit(x_train, y_train)

print('parameter terbaik:', grid_search.best_params_)
print('Best Score:', grid_search.best_score_)

parameter terbaik: {'max_depth': None, 'n_estimators': 50}
Best Score: 0.9416666666666667


In [36]:
#prediksi
new_data = pd.DataFrame({
    'sepal length (cm)': [5.1],
    'sepal width (cm)': [3.5],
    'petal length (cm)': [1.4],
    'petal width (cm)': [0.2]
})


new_data = scaler.transform(new_data)
prediction = model.predict(new_data)
print('Predicted Class:', iris.target_names[prediction][0])


Predicted Class: setosa
